### ISSUE TITLE
Correlation coefficient referred to as r^2

### ISSUE THREAD

**Issue by isobeldaley** [learn-co-curriculum/dsc-exploring-your-data-lab#1]
Under 'Checking for multicollinearity', Pearson's correlation coefficient is referred to as r^2.  Should be r

**Comment by sumedh10** [comment]
Fixed [here](https://github.com/learn-co-curriculum/dsc-exploring-your-data-lab/pull/2/commits/df797f205d5c2b0317bd83896812f32eaa86abda).
