### ISSUE TITLE
Data set mis-matched in text and answer key

### ISSUE THREAD

**Issue by AnnikaNoren** [learn-co-curriculum/dsc-exploring-your-data-lab#3]
The lab instructs us to use:
Load the dataset stored in the 'Lego_data_merged.csv' file into a DataFrame, df.

And this creates an error.

The answer key uses: 
df = pd.read_csv('Lego_dataset_cleaned.csv')

And that does not create an error.

**Comment by jessepisel** [comment]
Thanks for opening this issue @AnnikaNoren :wave:. I have clarified the instructions with commit 4f7c1e3ab64206d624ee6cbcf599a1135520b6d3.

I am closing this issue at this time.

**Comment by jessepisel** [comment]
Thanks for opening this @AnnikaNoren :wave:. This has been addressed by commit 4f7c1e3ab64206d624ee6cbcf599a1135520b6d3 and 6eefffec9fafec7b9a2c31b875c7ddb4614e300c but was never closed.

I am closing this issue at this time.
